name: Sync Tech Debt form to Project fields

on:
  issues:
    types: [opened, edited]

permissions:
  issues: read
  repository-projects: write
  contents: read

env:
  PROJECT_URL: https://github.com/users/Kiwasthal/projects/2

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Ensure issue is on the project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: ${{ env.PROJECT_URL }}
          github-token: ${{ secrets.PROJECT_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install script deps
        run: npm install @actions/core @actions/github
        env:
          CI: true

      - name: Run sync script
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_TOKEN || secrets.GITHUB_TOKEN }}
          PROJECT_URL: ${{ env.PROJECT_URL }}
        run: node .github/scripts/sync.js

      # Replaced by Node script above
